### ISSUE TITLE
测试代码中，a.com的疑惑。

### ISSUE THREAD

**Issue by yuguigang** [zqzhang0521/DomainTreeMatch#1]
运行原版测试代码，测试域名：【a.com】，是否在树上：true。如果尝试获取GroupInfo中Name字段为空，ID字段为-1。我的理解是，当测试域名在树上时，是否应当在GroupInfo获取到Name和ID字段，而不是默认？

**Comment by zqzhang0521** [comment]
1. 当测试域名在树上时，是否应当在GroupInfo获取到Name和ID字段，而不是默认？
          回答：是的，可以获取到Name和ID字段的，执行 tree.PreOrder(tmpDomain)，返回的对象是GroupInfo，属性值有name和id和code， 我贴的测试用例是方便测试，就直接tree.PreOrder(tmpDomain).getCode() 获取到Code值了。
2. 如果尝试获取GroupInfo中Name字段为空，ID字段为-1
          回答：这里构建二叉树时候，需要在业务中控制name字段为空的数据。
3. 请问下 你的业务中也有类似数据匹配么，使用当前的算法，数据处理是否有显著提高？有什么想法欢迎随时和我交流，也可以发我邮箱。
